### PR TITLE
♻️ Change type hints to support versions older than Python 3.9

### PR DESCRIPTION
**Pull request by odiseo0**
I tested these changes for Python 3.8.10, but I believe they work for 3.7 also

### CODE REVIEW

**Comment by Kludex** [comment]
What's the older version you're trying to run? This package only supports Python 3.8+.

**Comment by odiseo0** [comment]
3.8.10 was my lowest, I was running it on EBS
Note: It wasn't installed from pip

**Comment by Kludex** [comment]
What was the issue? Because `from __future__ import annotations` should allow this package to be compatible with Python 3.8.

**Comment by odiseo0** [comment]
Pylance was telling me that for example `list[Policy]` would generate a runtime exception, or that the `|` is for Python 3.9

**Pull request closed without merging**
